[[redirects]]
  from = "/api/*"
  to = "https://api.platform-test.website/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[build]
  # Use npm instead of bun for Netlify
  command = "npm run build"